In [0]:
#1
import numpy as np

In [0]:
#2
arr = []
for i in range(10):
  arr.append(i)
print(arr)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [0]:
#3
ar = []
for i in range(3):
  ar.append(True)
arr = np.array([ar,ar])
print(arr)


[[ True  True  True]
 [ True  True  True]]


In [0]:
#4
ar = []
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
for i in arr:
  if i & 0x1:
    ar.append(i)
print(ar)

[1, 3, 5, 7, 9]


In [0]:
#5
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
for i in arr:
  if i & 0x1:
    arr[i] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [0]:
#6
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
ar = []
for i in arr:
  if i & 0x1:
    ar.append(-1)
  else:
    ar.append(i)
ar = np.array(ar)
print(arr)
print(ar)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [0]:
#7
arr = np.arange(10)
print(arr.reshape((2,5)))

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [0]:
#8
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

print(np.vstack((a,b)))

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [0]:
#9
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

print(np.hstack((a,b)))

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [3]:
#10
a = np.array([1,2,3])

print(np.r_[np.repeat(a, 3), np.tile(a, 3)])

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [4]:
#11
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))

[2 4]


In [14]:
#12
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
print(np.setdiff1d(a,b))

[1 2 3 4]


In [15]:
#13
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

print(np.where(a == b))

(array([1, 3, 5, 7]),)


In [21]:
#14
a = np.array([2, 6, 1, 9, 10, 3, 27])

index = np.where(np.logical_and(a > 4, a < 11))
print(a[index])

[ 6  9 10]


In [26]:
#15
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

# maxx(1, 5) => 5

def pair_max(a,b):
  res = []
  for x in range(a.size):
    if a[x] >= b[x]:
      res.append(a[x])
    else:
      res.append(b[x])
  return np.array(res)

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

print(pair_max(a, b))

pair_max = np.vectorize(maxx, otypes=[float])

print(pair_max(a,b))

[6 7 9 8 9 7 5]
[6. 7. 9. 8. 9. 7. 5.]


In [5]:
#16
arr = np.arange(9).reshape(3,3)
print(arr)

arr[:,[0, 1]] = arr[:,[1, 0]]
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [6]:
#17
arr = np.arange(9).reshape(3,3)
print(arr)

arr[[0,1],:] = arr[[1,0],:]
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [24]:
#18
arr = np.arange(9).reshape(3,3)
print(arr)

arr = arr[::-1]
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [11]:
#19
arr = np.arange(9).reshape(3,3)
print(arr)

arr = arr[:,::-1]
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [22]:
#20
arr = np.random.uniform(5,10, size=(5,3)) 
print(arr)

[[6.13202319 7.36935794 5.75383119]
 [5.3266354  9.09477782 8.75849201]
 [9.30602094 6.28706888 6.44157854]
 [8.63450229 6.07045496 7.72090421]
 [8.95141818 7.87633675 8.18525702]]


In [30]:
#21
rand_arr = np.random.random((5,3))
print(np.around(rand_arr, decimals=3))

np.set_printoptions(precision=3)
print(rand_arr)

[[0.547 0.323 0.579]
 [0.943 0.94  0.475]
 [0.589 0.047 0.251]
 [0.722 0.915 0.14 ]
 [0.574 0.139 0.929]]
[[0.547 0.323 0.579]
 [0.943 0.94  0.475]
 [0.589 0.047 0.251]
 [0.722 0.915 0.14 ]
 [0.574 0.139 0.929]]


In [35]:
#22
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3

np.set_printoptions(suppress=True, precision=6)
print(rand_arr)

[[0.000543 0.000278 0.000425]
 [0.000845 0.000005 0.000122]
 [0.000671 0.000826 0.000137]]


In [37]:
#23
a = np.arange(15)

np.set_printoptions(threshold=6)
print(a)

[ 0  1  2 ... 12 13 14]


In [41]:
#24
np.set_printoptions(threshold=6)
a = np.arange(15)
np.set_printoptions(threshold=np.inf)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [44]:
#25
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

print(iris[:5])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']]
